const express = require('express');

const app = express();

app.get('/', (req, res) => {
    res.status = 200
    res.json({ code: 200, message: "API pour le TP android" })
});

app.get('/orders', (req, res) => {
    res.status(200)
    res.json({
        code: 200, data: {
            "commands": [
                {
                    "meals": [
                        {
                            idMeal: "52772",
                            strMeal: "Teriyaki Chicken Casserole",
                            strDrinkAlternate: null,
                            strCategory: "Chicken",
                            strArea: "Japanese",
                            strInstructions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray. Combine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling. Meanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat. Place the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks. *Meanwhile, steam or cook the vegetables according to package directions. Add the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
                            strMealThumb: "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
                            strTags: "Meat,Casserole",
                            strYoutube: "https://www.youtube.com/watch?v=4aZr5hZXP_s",
                            strIngredient1: "soy sauce",
                            strIngredient2: "water",
                            strIngredient3: "brown sugar",
                            strIngredient4: "ground ginger",
                            strIngredient5: "minced garlic",
                            strIngredient6: "cornstarch",
                            strIngredient7: "chicken breasts",
                            strIngredient8: "stir-fry vegetables",
                            strIngredient9: "brown rice",
                            strIngredient10: "",
                            strIngredient11: "",
                            strIngredient12: "",
                            strIngredient13: "",
                            strIngredient14: "",
                            strIngredient15: "",
                            strIngredient16: null,
                            strIngredient17: null,
                            strIngredient18: null,
                            strIngredient19: null,
                            strIngredient20: null,
                            strMeasure1: "3/4 cup",
                            strMeasure2: "1/2 cup",
                            strMeasure3: "1/4 cup",
                            strMeasure4: "1/2 teaspoon",
                            strMeasure5: "1/2 teaspoon",
                            strMeasure6: "4 Tablespoons",
                            strMeasure7: "2",
                            strMeasure8: "1 (12 oz.)",
                            strMeasure9: "3 cups",
                            strMeasure10: "",
                            strMeasure11: "",
                            strMeasure12: "",
                            strMeasure13: "",
                            strMeasure14: "",
                            strMeasure15: "",
                            strMeasure16: null,
                            strMeasure17: null,
                            strMeasure18: null,
                            strMeasure19: null,
                            strMeasure20: null,
                            strSource: null,
                            strImageSource: null,
                            strCreativeCommonsConfirmed: null,
                            dateModified: null
                        },
                        {
                            idMeal: "52772",
                            strMeal: "Teriyaki Chicken Casserole",
                            strDrinkAlternate: null,
                            strCategory: "Chicken",
                            strArea: "Japanese",
                            strInstructions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray. Combine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling. Meanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat. Place the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks. *Meanwhile, steam or cook the vegetables according to package directions. Add the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
                            strMealThumb: "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
                            strTags: "Meat,Casserole",
                            strYoutube: "https://www.youtube.com/watch?v=4aZr5hZXP_s",
                            strIngredient1: "soy sauce",
                            strIngredient2: "water",
                            strIngredient3: "brown sugar",
                            strIngredient4: "ground ginger",
                            strIngredient5: "minced garlic",
                            strIngredient6: "cornstarch",
                            strIngredient7: "chicken breasts",
                            strIngredient8: "stir-fry vegetables",
                            strIngredient9: "brown rice",
                            strIngredient10: "",
                            strIngredient11: "",
                            strIngredient12: "",
                            strIngredient13: "",
                            strIngredient14: "",
                            strIngredient15: "",
                            strIngredient16: null,
                            strIngredient17: null,
                            strIngredient18: null,
                            strIngredient19: null,
                            strIngredient20: null,
                            strMeasure1: "3/4 cup",
                            strMeasure2: "1/2 cup",
                            strMeasure3: "1/4 cup",
                            strMeasure4: "1/2 teaspoon",
                            strMeasure5: "1/2 teaspoon",
                            strMeasure6: "4 Tablespoons",
                            strMeasure7: "2",
                            strMeasure8: "1 (12 oz.)",
                            strMeasure9: "3 cups",
                            strMeasure10: "",
                            strMeasure11: "",
                            strMeasure12: "",
                            strMeasure13: "",
                            strMeasure14: "",
                            strMeasure15: "",
                            strMeasure16: null,
                            strMeasure17: null,
                            strMeasure18: null,
                            strMeasure19: null,
                            strMeasure20: null,
                            strSource: null,
                            strImageSource: null,
                            strCreativeCommonsConfirmed: null,
                            dateModified: null
                        },
                        {
                            idMeal: "53038",
                            strMeal: "Mustard champ",
                            strDrinkAlternate: null,
                            strCategory: "Side",
                            strArea: "Irish",
                            strInstructions: "STEP 1 Boil the potatoes for 15 mins or until tender. Drain, then mash. STEP 2 Heat the milk and half the butter in the corner of the pan, then beat into the mash, along with the wholegrain mustard. STEP 3 Gently fry the spring onions in the remaining butter for 2 mins until just soft but still a perky green. Fold into the mash and serve. Great with gammon or to top a fish pie.",
                            strMealThumb: "https://www.themealdb.com/images/media/meals/o7p9581608589317.jpg",
                            strTags: null,
                            strYoutube: "https://www.youtube.com/watch?v=_iKllHSC978",
                            strIngredient1: "Potatoes",
                            strIngredient2: "Milk",
                            strIngredient3: "Butter",
                            strIngredient4: "Mustard",
                            strIngredient5: "Spring Onions",
                            strIngredient6: "Spring Onions",
                            strIngredient7: "",
                            strIngredient8: "",
                            strIngredient9: "",
                            strIngredient10: "",
                            strIngredient11: "",
                            strIngredient12: "",
                            strIngredient13: "",
                            strIngredient14: "",
                            strIngredient15: "",
                            strIngredient16: "",
                            strIngredient17: "",
                            strIngredient18: "",
                            strIngredient19: "",
                            strIngredient20: "",
                            strMeasure1: "1kg",
                            strMeasure2: "200ml",
                            strMeasure3: "50g",
                            strMeasure4: "2 tbs",
                            strMeasure5: "Bunch",
                            strMeasure6: "Bunch",
                            strMeasure7: " ",
                            strMeasure8: " ",
                            strMeasure9: " ",
                            strMeasure10: " ",
                            strMeasure11: " ",
                            strMeasure12: " ",
                            strMeasure13: " ",
                            strMeasure14: " ",
                            strMeasure15: " ",
                            strMeasure16: " ",
                            strMeasure17: " ",
                            strMeasure18: " ",
                            strMeasure19: " ",
                            strMeasure20: " ",
                            strSource: "https://www.bbcgoodfood.com/recipes/mustard-champ",
                            strImageSource: null,
                            strCreativeCommonsConfirmed: null,
                            dateModified: null
                        }
                    ],
                    "price": 20.53,
                    "dueDate": "2021-02-21T20:00:00.000Z"
                },
                {
                    "meals": [
                        {
                            idMeal: "53032",
                            strMeal: "Tonkatsu pork",
                            strDrinkAlternate: null,
                            strCategory: "Pork",
                            strArea: "Japanese",
                            strInstructions: "STEP 1 Remove the large piece of fat on the edge of each pork loin, then bash each of the loins between two pieces of baking parchment until around 1cm in thickness – you can do this using a meat tenderiser or a rolling pin. Once bashed, use your hands to reshape the meat to its original shape and thickness – this step will ensure the meat is as succulent as possible. STEP 2 Put the flour, eggs and panko breadcrumbs into three separate wide-rimmed bowls. Season the meat, then dip first in the flour, followed by the eggs, then the breadcrumbs. STEP 3 In a large frying or sauté pan, add enough oil to come 2cm up the side of the pan. Heat the oil to 180C – if you don’t have a thermometer, drop a bit of panko into the oil and if it sinks a little then starts to fry, the oil is ready. Add two pork chops and cook for 1 min 30 secs on each side, then remove and leave to rest on a wire rack for 5 mins. Repeat with the remaining pork chops. STEP 4 While the pork is resting, make the sauce by whisking the ingredients together, adding a splash of water if it’s particularly thick. Slice the tonkatsu and serve drizzled with the sauce.",
                            strMealThumb: "https://www.themealdb.com/images/media/meals/lwsnkl1604181187.jpg",
                            strTags: null,
                            strYoutube: "https://www.youtube.com/watch?v=aASr5x0d3Ys",
                            strIngredient1: "Pork Chops",
                            strIngredient2: "Flour",
                            strIngredient3: "Eggs",
                            strIngredient4: "Breadcrumbs",
                            strIngredient5: "Vegetable Oil",
                            strIngredient6: "Tomato Ketchup",
                            strIngredient7: "Worcestershire Sauce",
                            strIngredient8: "Oyster Sauce",
                            strIngredient9: "Caster Sugar",
                            strIngredient10: "",
                            strIngredient11: "",
                            strIngredient12: "",
                            strIngredient13: "",
                            strIngredient14: "",
                            strIngredient15: "",
                            strIngredient16: "",
                            strIngredient17: "",
                            strIngredient18: "",
                            strIngredient19: "",
                            strIngredient20: "",
                            strMeasure1: "4",
                            strMeasure2: "100g ",
                            strMeasure3: "2 Beaten ",
                            strMeasure4: "100g ",
                            strMeasure5: "Fry",
                            strMeasure6: "2 tbs",
                            strMeasure7: "2 tbs",
                            strMeasure8: "1 tbs",
                            strMeasure9: "2 tblsp ",
                            strMeasure10: " ",
                            strMeasure11: " ",
                            strMeasure12: " ",
                            strMeasure13: " ",
                            strMeasure14: " ",
                            strMeasure15: " ",
                            strMeasure16: " ",
                            strMeasure17: " ",
                            strMeasure18: " ",
                            strMeasure19: " ",
                            strMeasure20: " ",
                            strSource: "https://www.bbcgoodfood.com/recipes/tonkatsu-pork",
                            strImageSource: null,
                            strCreativeCommonsConfirmed: null,
                            dateModified: null
                        },
                        {
                            idMeal: "53032",
                            strMeal: "Tonkatsu pork",
                            strDrinkAlternate: null,
                            strCategory: "Pork",
                            strArea: "Japanese",
                            strInstructions: "STEP 1 Remove the large piece of fat on the edge of each pork loin, then bash each of the loins between two pieces of baking parchment until around 1cm in thickness – you can do this using a meat tenderiser or a rolling pin. Once bashed, use your hands to reshape the meat to its original shape and thickness – this step will ensure the meat is as succulent as possible. STEP 2 Put the flour, eggs and panko breadcrumbs into three separate wide-rimmed bowls. Season the meat, then dip first in the flour, followed by the eggs, then the breadcrumbs. STEP 3 In a large frying or sauté pan, add enough oil to come 2cm up the side of the pan. Heat the oil to 180C – if you don’t have a thermometer, drop a bit of panko into the oil and if it sinks a little then starts to fry, the oil is ready. Add two pork chops and cook for 1 min 30 secs on each side, then remove and leave to rest on a wire rack for 5 mins. Repeat with the remaining pork chops. STEP 4 While the pork is resting, make the sauce by whisking the ingredients together, adding a splash of water if it’s particularly thick. Slice the tonkatsu and serve drizzled with the sauce.",
                            strMealThumb: "https://www.themealdb.com/images/media/meals/lwsnkl1604181187.jpg",
                            strTags: null,
                            strYoutube: "https://www.youtube.com/watch?v=aASr5x0d3Ys",
                            strIngredient1: "Pork Chops",
                            strIngredient2: "Flour",
                            strIngredient3: "Eggs",
                            strIngredient4: "Breadcrumbs",
                            strIngredient5: "Vegetable Oil",
                            strIngredient6: "Tomato Ketchup",
                            strIngredient7: "Worcestershire Sauce",
                            strIngredient8: "Oyster Sauce",
                            strIngredient9: "Caster Sugar",
                            strIngredient10: "",
                            strIngredient11: "",
                            strIngredient12: "",
                            strIngredient13: "",
                            strIngredient14: "",
                            strIngredient15: "",
                            strIngredient16: "",
                            strIngredient17: "",
                            strIngredient18: "",
                            strIngredient19: "",
                            strIngredient20: "",
                            strMeasure1: "4",
                            strMeasure2: "100g ",
                            strMeasure3: "2 Beaten ",
                            strMeasure4: "100g ",
                            strMeasure5: "Fry",
                            strMeasure6: "2 tbs",
                            strMeasure7: "2 tbs",
                            strMeasure8: "1 tbs",
                            strMeasure9: "2 tblsp ",
                            strMeasure10: " ",
                            strMeasure11: " ",
                            strMeasure12: " ",
                            strMeasure13: " ",
                            strMeasure14: " ",
                            strMeasure15: " ",
                            strMeasure16: " ",
                            strMeasure17: " ",
                            strMeasure18: " ",
                            strMeasure19: " ",
                            strMeasure20: " ",
                            strSource: "https://www.bbcgoodfood.com/recipes/tonkatsu-pork",
                            strImageSource: null,
                            strCreativeCommonsConfirmed: null,
                            dateModified: null
                        },
                        {
                            idMeal: "53032",
                            strMeal: "Tonkatsu pork",
                            strDrinkAlternate: null,
                            strCategory: "Pork",
                            strArea: "Japanese",
                            strInstructions: "STEP 1 Remove the large piece of fat on the edge of each pork loin, then bash each of the loins between two pieces of baking parchment until around 1cm in thickness – you can do this using a meat tenderiser or a rolling pin. Once bashed, use your hands to reshape the meat to its original shape and thickness – this step will ensure the meat is as succulent as possible. STEP 2 Put the flour, eggs and panko breadcrumbs into three separate wide-rimmed bowls. Season the meat, then dip first in the flour, followed by the eggs, then the breadcrumbs. STEP 3 In a large frying or sauté pan, add enough oil to come 2cm up the side of the pan. Heat the oil to 180C – if you don’t have a thermometer, drop a bit of panko into the oil and if it sinks a little then starts to fry, the oil is ready. Add two pork chops and cook for 1 min 30 secs on each side, then remove and leave to rest on a wire rack for 5 mins. Repeat with the remaining pork chops. STEP 4 While the pork is resting, make the sauce by whisking the ingredients together, adding a splash of water if it’s particularly thick. Slice the tonkatsu and serve drizzled with the sauce.",
                            strMealThumb: "https://www.themealdb.com/images/media/meals/lwsnkl1604181187.jpg",
                            strTags: null,
                            strYoutube: "https://www.youtube.com/watch?v=aASr5x0d3Ys",
                            strIngredient1: "Pork Chops",
                            strIngredient2: "Flour",
                            strIngredient3: "Eggs",
                            strIngredient4: "Breadcrumbs",
                            strIngredient5: "Vegetable Oil",
                            strIngredient6: "Tomato Ketchup",
                            strIngredient7: "Worcestershire Sauce",
                            strIngredient8: "Oyster Sauce",
                            strIngredient9: "Caster Sugar",
                            strIngredient10: "",
                            strIngredient11: "",
                            strIngredient12: "",
                            strIngredient13: "",
                            strIngredient14: "",
                            strIngredient15: "",
                            strIngredient16: "",
                            strIngredient17: "",
                            strIngredient18: "",
                            strIngredient19: "",
                            strIngredient20: "",
                            strMeasure1: "4",
                            strMeasure2: "100g ",
                            strMeasure3: "2 Beaten ",
                            strMeasure4: "100g ",
                            strMeasure5: "Fry",
                            strMeasure6: "2 tbs",
                            strMeasure7: "2 tbs",
                            strMeasure8: "1 tbs",
                            strMeasure9: "2 tblsp ",
                            strMeasure10: " ",
                            strMeasure11: " ",
                            strMeasure12: " ",
                            strMeasure13: " ",
                            strMeasure14: " ",
                            strMeasure15: " ",
                            strMeasure16: " ",
                            strMeasure17: " ",
                            strMeasure18: " ",
                            strMeasure19: " ",
                            strMeasure20: " ",
                            strSource: "https://www.bbcgoodfood.com/recipes/tonkatsu-pork",
                            strImageSource: null,
                            strCreativeCommonsConfirmed: null,
                            dateModified: null
                        },
                        {
                            idMeal: "53034",
                            strMeal: "Japanese Katsudon",
                            strDrinkAlternate: null,
                            strCategory: "Pork",
                            strArea: "Japanese",
                            strInstructions: "STEP 1 Heat the oil in a pan, fry the sliced onion until golden brown, then add the tonkatsu (see recipe here), placing it in the middle of the pan. Mix the dashi, soy, mirin and sugar together and tip three-quarters of the mixture around the tonkatsu. Sizzle for a couple of mins so the sauce thickens a little and the tonkatsu reheats. STEP 2 Tip the beaten eggs around the tonkatsu and cook for 2-3 mins until the egg is cooked through but still a little runny. Divide the rice between two bowls, then top each with half the egg and tonkatsu mix, sprinkle over the chives and serve immediately, drizzling with a little more soy if you want an extra umami kick.",
                            strMealThumb: "https://www.themealdb.com/images/media/meals/d8f6qx1604182128.jpg",
                            strTags: null,
                            strYoutube: "https://www.youtube.com/watch?v=voE-MBJqBVk",
                            strIngredient1: "Vegetable Oil",
                            strIngredient2: "Onion",
                            strIngredient3: "Pork",
                            strIngredient4: "Vegetable Stock",
                            strIngredient5: "Soy Sauce",
                            strIngredient6: "Mirin",
                            strIngredient7: "Sugar",
                            strIngredient8: "Eggs",
                            strIngredient9: "Sushi Rice",
                            strIngredient10: "Chives",
                            strIngredient11: "",
                            strIngredient12: "",
                            strIngredient13: "",
                            strIngredient14: "",
                            strIngredient15: "",
                            strIngredient16: "",
                            strIngredient17: "",
                            strIngredient18: "",
                            strIngredient19: "",
                            strIngredient20: "",
                            strMeasure1: "1 tbs",
                            strMeasure2: "1 large",
                            strMeasure3: "1 chopped",
                            strMeasure4: "150ml",
                            strMeasure5: "1 tbs",
                            strMeasure6: "1 tsp ",
                            strMeasure7: "1 tsp ",
                            strMeasure8: "2 Beaten ",
                            strMeasure9: "200g",
                            strMeasure10: "Chopped",
                            strMeasure11: " ",
                            strMeasure12: " ",
                            strMeasure13: " ",
                            strMeasure14: " ",
                            strMeasure15: " ",
                            strMeasure16: " ",
                            strMeasure17: " ",
                            strMeasure18: " ",
                            strMeasure19: " ",
                            strMeasure20: " ",
                            strSource: "https://www.bbcgoodfood.com/recipes/japanese-katsudon",
                            strImageSource: null,
                            strCreativeCommonsConfirmed: null,
                            dateModified: null
                        },
                        {
                            idMeal: "53034",
                            strMeal: "Japanese Katsudon",
                            strDrinkAlternate: null,
                            strCategory: "Pork",
                            strArea: "Japanese",
                            strInstructions: "STEP 1 Heat the oil in a pan, fry the sliced onion until golden brown, then add the tonkatsu (see recipe here), placing it in the middle of the pan. Mix the dashi, soy, mirin and sugar together and tip three-quarters of the mixture around the tonkatsu. Sizzle for a couple of mins so the sauce thickens a little and the tonkatsu reheats. STEP 2 Tip the beaten eggs around the tonkatsu and cook for 2-3 mins until the egg is cooked through but still a little runny. Divide the rice between two bowls, then top each with half the egg and tonkatsu mix, sprinkle over the chives and serve immediately, drizzling with a little more soy if you want an extra umami kick.",
                            strMealThumb: "https://www.themealdb.com/images/media/meals/d8f6qx1604182128.jpg",
                            strTags: null,
                            strYoutube: "https://www.youtube.com/watch?v=voE-MBJqBVk",
                            strIngredient1: "Vegetable Oil",
                            strIngredient2: "Onion",
                            strIngredient3: "Pork",
                            strIngredient4: "Vegetable Stock",
                            strIngredient5: "Soy Sauce",
                            strIngredient6: "Mirin",
                            strIngredient7: "Sugar",
                            strIngredient8: "Eggs",
                            strIngredient9: "Sushi Rice",
                            strIngredient10: "Chives",
                            strIngredient11: "",
                            strIngredient12: "",
                            strIngredient13: "",
                            strIngredient14: "",
                            strIngredient15: "",
                            strIngredient16: "",
                            strIngredient17: "",
                            strIngredient18: "",
                            strIngredient19: "",
                            strIngredient20: "",
                            strMeasure1: "1 tbs",
                            strMeasure2: "1 large",
                            strMeasure3: "1 chopped",
                            strMeasure4: "150ml",
                            strMeasure5: "1 tbs",
                            strMeasure6: "1 tsp ",
                            strMeasure7: "1 tsp ",
                            strMeasure8: "2 Beaten ",
                            strMeasure9: "200g",
                            strMeasure10: "Chopped",
                            strMeasure11: " ",
                            strMeasure12: " ",
                            strMeasure13: " ",
                            strMeasure14: " ",
                            strMeasure15: " ",
                            strMeasure16: " ",
                            strMeasure17: " ",
                            strMeasure18: " ",
                            strMeasure19: " ",
                            strMeasure20: " ",
                            strSource: "https://www.bbcgoodfood.com/recipes/japanese-katsudon",
                            strImageSource: null,
                            strCreativeCommonsConfirmed: null,
                            dateModified: null
                        }
                    ],
                    "price": 150.29,
                    "dueDate": "2021-02-26T21:30:00.000Z"
                }
            ]
        }
    })
});

app.listen(3000)